[workspace]
resolver = "2"

members = [
    "projects/hello_rust",
    "projects/person_manager",
    "projects/lost_crypto_drive",
    "projects/rust_tests",
    "projects/cloudflare_worker_hello_rust",
]