name: Deploy Cloudflare Worker

on:
  workflow_run:
    workflows: ["Rust Tests"]
    types:
      - completed
  push:
    paths:
      - 'projects/cloudflare_worker_hello_rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    name: Do Nothing
    steps:
      - name: Do Nothing
        run: echo "Do Nothing"
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy Worker Hello Rust
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: "projects/cloudflare_worker_hello_rust"