name: Deploy Cloudflare Worker

on:
  workflow_run:
    workflows: ["Rust Tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  check-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      run-job: ${{ steps.path-check.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check for file changes in the commit
        id: path-check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q 'projects/cloudflare_worker_hello_rust'; then
            echo "result=true" >> $GITHUB_ENV
          else
            echo "result=false" >> $GITHUB_ENV
          fi

  deploy:
    needs: check-commit
    if: needs.check-commit.outputs.run-job == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy Worker Hello Rust
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: "projects/cloudflare_worker_hello_rust"