name: Deploy Cloudflare Worker

on:
  workflow_run:
    workflows: ["Rust Tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  check-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      run-job: ${{ steps.filter.outputs.run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check for file changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changes:
              - 'projects/cloudflare_worker_hello_rust/**'

  deploy:
    needs: check-changes
    if: needs.check-changes.outputs.run-job == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy Worker Hello Rust
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: "projects/cloudflare_worker_hello_rust"